## Import libraries ##

In [19]:
import pandas as pd
import numpy as np

## Upload CSV

In [20]:
in_kind=pd.read_csv('In-Kind Tracking.csv')

In [21]:
in_kind.head(0)

Empty DataFrame
Columns: [Agency, Site, Classroom, Volunteer Name, Transaction Date, Service Type, Service Description, Program, Quantity, Rate, Total Amount, Funding Name]
Index: []

## Drop Volunteer Name column to remove PII from data visualizations

In [22]:
in_kind = in_kind.drop(columns=['Volunteer Name'])

## Verify Volunteer Name column is dropped

In [23]:
in_kind.head(0)

Empty DataFrame
Columns: [Agency, Site, Classroom, Transaction Date, Service Type, Service Description, Program, Quantity, Rate, Total Amount, Funding Name]
Index: []

## Define and replace Funding Names to create more standardized and readable names

In [24]:
mapping = {
    '[REDACTED]': 'Funding Source 1',
    '[REDACTED]': 'Funding Source 1',
    '[REDACTED]': 'Funding Source 1',
    '[REDACTED]': 'Funding Source 1',
    '[REDACTED]': 'Funding Source 1',
    '[REDACTED]': 'Funding Source 1',
    '[REDACTED]': 'Funding Source 1',
    '[REDACTED]': 'Funding Source 1',
    '[REDACTED]': 'Funding Source 1'
}

in_kind['Funding Name'] = in_kind['Funding Name'].replace(mapping)

## Create new column (Reporting Category) to separate state-level funding categories

In [25]:
in_kind["Reporting Category"] = np.where(
    in_kind["Program"].str.contains("[REDACTED]", case=False, na=False) &
    in_kind["Program"].str.contains("[REDACTED]", case=False, na=False),
    "[REDACTED] State",
    np.where(
        in_kind["Program"].str.contains("[REDACTED]", case=False, na=False) &
        in_kind["Program"].str.contains("[REDACTED]", case=False, na=False),
        "[REDACTED] State",
        "Other"
    )
)

## Verify new column (Reporting Category) has been added

In [ ]:
in_kind.head(5)

## Upload cleaned dataset to Jupyter repository

In [27]:
in_kind.to_csv('In-Kind Tracking.csv', index=False)